version: '3.0'

services:
  mongo:    
    image: mongo:4.0
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: akkaTrader

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8031:8081
    depends_on:
      - "mongo"

  lighthouse:
    image: petabridge/lighthouse:latest
    hostname: lighthouse
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "AkkaTrader"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"

  tradeprocessor:
    image: akka.cqrs.tradeprocessor
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
      MONGO_CONNECTION_STR: "mongodb://mongo:27017/akkaTrader"
    restart: on-failure
    depends_on:
      - "mongo"
      - "lighthouse"

  traders:
    image: akka.cqrs.traders
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  lighthouse_pricing:
    image: petabridge/lighthouse:latest
    hostname: lighthouse_pricing
    ports:
      - '9111:9110'
      - '4054:4054'
    environment:
      ACTORSYSTEM: "AkkaPricing"
      CLUSTER_PORT: 4054
      CLUSTER_IP: "lighthouse_pricing"
      CLUSTER_SEEDS: "akka.tcp://AkkaPricing@lighthouse_pricing:4054"

  pricing-engine:
    image: akka.cqrs.pricing
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaPricing@lighthouse_pricing:4054"
      CLUSTER_PORT: 6055
      MONGO_CONNECTION_STR: "mongodb://mongo:27017/akkaTrader"
    restart: on-failure
    depends_on:
      - "mongo"
      - "lighthouse_pricing"