version: '3.7'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sql
    restart: always
    ports:
      - '1633:1433'
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "This!IsOpenSource1"

  lighthouse:
    image: petabridge/lighthouse:latest
    hostname: lighthouse
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "AkkaTrader"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"

  tradeprocessor:
    image: akka.cqrs.tradeprocessor
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
      SQL_CONNECTION_STR: "Server=sql,1433;User Id=sa;Password=This!IsOpenSource1;TrustServerCertificate=true"
      SQL_PROVIDER_NAME: "SqlServer.2022"
    restart: on-failure
    depends_on:
      - "sql"
      - "lighthouse"

  traders:
    image: akka.cqrs.traders
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
    restart: on-failure
    depends_on:
      - "lighthouse"

  lighthouse_pricing:
    image: petabridge/lighthouse:latest
    hostname: lighthouse_pricing
    ports:
      - '9111:9110'
      - '4054:4054'
    environment:
      ACTORSYSTEM: "AkkaPricing"
      CLUSTER_PORT: 4054
      CLUSTER_IP: "lighthouse_pricing"
      CLUSTER_SEEDS: "akka.tcp://AkkaPricing@lighthouse_pricing:4054"

  pricing-engine:
    image: akka.cqrs.pricing
    deploy:
      replicas: 3
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaPricing@lighthouse_pricing:4054"
      CLUSTER_PORT: 6055
      SQL_CONNECTION_STR: "Server=sql,1433;User Id=sa;Password=This!IsOpenSource1;TrustServerCertificate=true"
      SQL_PROVIDER_NAME: "SqlServer.2022"
    restart: on-failure
    depends_on:
      - "sql"
      - "lighthouse_pricing"